import "./globals.css";
import Navbar from "./components/Navbar.jsx";
import Footer from "./components/Footer.jsx";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-y-auto">
      <body className="overflow-x-hidden ">
      <Navbar />
        {children}
      <Footer />
      </body>
    </html>
  );
}
